package algo

var MEDIUM_LIST = []string{
	"[1. 两数之和 - 力扣（LeetCode）](https://leetcode.cn/problems/two-sum/description/)",
	"   1. [49. 字母异位词分组](https://leetcode.cn/problems/group-anagrams/)",
	"	2. [128. 最长连续序列](https://leetcode.cn/problems/longest-consecutive-sequence/)",
	"	3. [11. 盛最多水的容器](https://leetcode.cn/problems/container-with-most-water/)",
	"	4. [15. 三数之和](https://leetcode.cn/problems/3sum/)",
	"	5. [3. 无重复字符的最长子串](https://leetcode.cn/problems/longest-substring-without-repeating-characters/)",
	"	6. [438. 找到字符串中所有字母异位词](https://leetcode.cn/problems/find-all-anagrams-in-a-string/)",
	"	7. [560. 和为 K 的子数组](https://leetcode.cn/problems/subarray-sum-equals-k/)",
	"	8. [53. 最大子数组和](https://leetcode.cn/problems/maximum-subarray/)",
	"	9. [56. 合并区间](https://leetcode.cn/problems/merge-intervals/)",
	"	10. [189. 轮转数组](https://leetcode.cn/problems/rotate-array/)",
	"	11. [238. 除自身以外数组的乘积](https://leetcode.cn/problems/product-of-array-except-self/)",
	"	12. [73. 矩阵置零](https://leetcode.cn/problems/set-matrix-zeroes/)",
	"	13. [54. 螺旋矩阵](https://leetcode.cn/problems/spiral-matrix/)",
	"	14. [48. 旋转图像](https://leetcode.cn/problems/rotate-image/)",
	"	15. [240. 搜索二维矩阵 II](https://leetcode.cn/problems/search-a-2d-matrix-ii/)",
	"	16. [142. 环形链表 II](https://leetcode.cn/problems/linked-list-cycle-ii/)",
	"	17. [2. 两数相加](https://leetcode.cn/problems/add-two-numbers/)",
	"	18. [19. 删除链表的倒数第 N 个结点](https://leetcode.cn/problems/remove-nth-node-from-end-of-list/)",
	"	19. [24. 两两交换链表中的节点](https://leetcode.cn/problems/swap-nodes-in-pairs/)",
	"	20. [138. 随机链表的复制](https://leetcode.cn/problems/copy-list-with-random-pointer/)",
	"	21. [148. 排序链表](https://leetcode.cn/problems/sort-list/)",
	"	22. [146. LRU 缓存](https://leetcode.cn/problems/lru-cache/)",
	"	23. [102. 二叉树的层序遍历](https://leetcode.cn/problems/binary-tree-level-order-traversal/)",
	"	24. [98. 验证二叉搜索树](https://leetcode.cn/problems/validate-binary-search-tree/)",
	"	25. [230. 二叉搜索树中第 K 小的元素](https://leetcode.cn/problems/kth-smallest-element-in-a-bst/)",
	"	26. [199. 二叉树的右视图](https://leetcode.cn/problems/binary-tree-right-side-view/)",
	"	27. [114. 二叉树展开为链表](https://leetcode.cn/problems/flatten-binary-tree-to-linked-list/)",
	"	28. [105. 从前序与中序遍历序列构造二叉树](https://leetcode.cn/problems/construct-binary-tree-from-preorder-and-inorder-traversal/)",
	"	29. [437. 路径总和 III](https://leetcode.cn/problems/path-sum-iii/)",
	"	30. [236. 二叉树的最近公共祖先](https://leetcode.cn/problems/lowest-common-ancestor-of-a-binary-tree/)",
	"	31. [200. 岛屿数量](https://leetcode.cn/problems/number-of-islands/)",
	"	32. [208. 实现 Trie (前缀树)](https://leetcode.cn/problems/implement-trie-prefix-tree/)",
	"	33. [207. 课程表](https://leetcode.cn/problems/course-schedule/)",
	"	34. [994. 腐烂的橘子](https://leetcode.cn/problems/rotting-oranges/)",
	"	35. [46. 全排列](https://leetcode.cn/problems/permutations/)",
	"	36. [78. 子集](https://leetcode.cn/problems/subsets/)",
	"	37. [17. 电话号码的字母组合](https://leetcode.cn/problems/letter-combinations-of-a-phone-number/)",
	"	38. [39. 组合总和](https://leetcode.cn/problems/combination-sum/)",
	"	39. [22. 括号生成](https://leetcode.cn/problems/generate-parentheses/)",
	"	40. [79. 单词搜索](https://leetcode.cn/problems/word-search/)",
	"	41. [131. 分割回文串](https://leetcode.cn/problems/palindrome-partitioning/)",
	"	42. [74. 搜索二维矩阵](https://leetcode.cn/problems/search-a-2d-matrix/)",
	"	43. [34. 在排序数组中查找元素的第一个和最后一个位置](https://leetcode.cn/problems/find-first-and-last-position-of-element-in-sorted-array/)",
	"	44. [33. 搜索旋转排序数组](https://leetcode.cn/problems/search-in-rotated-sorted-array/)",
	"	45. [153. 寻找旋转排序数组中的最小值](https://leetcode.cn/problems/find-minimum-in-rotated-sorted-array/)",
	"	46. [155. 最小栈](https://leetcode.cn/problems/min-stack/)",
	"	47. [394. 字符串解码](https://leetcode.cn/problems/decode-string/)",
	"	48. [739. 每日温度](https://leetcode.cn/problems/daily-temperatures/)",
	"	49. [55. 跳跃游戏](https://leetcode.cn/problems/jump-game/)",
	"	50. [45. 跳跃游戏 II](https://leetcode.cn/problems/jump-game-ii/)",
	"	51. [763. 划分字母区间](https://leetcode.cn/problems/partition-labels/)",
	"	52. [198. 打家劫舍](https://leetcode.cn/problems/house-robber/)",
	"	53. [279. 完全平方数](https://leetcode.cn/problems/perfect-squares/)",
	"	54. [322. 零钱兑换](https://leetcode.cn/problems/coin-change/)",
	"	55. [139. 单词拆分](https://leetcode.cn/problems/word-break/)",
	"	56. [300. 最长递增子序列](https://leetcode.cn/problems/longest-increasing-subsequence/)",
	"	57. [152. 乘积最大子数组](https://leetcode.cn/problems/maximum-product-subarray/)",
	"	58. [416. 分割等和子集](https://leetcode.cn/problems/partition-equal-subset-sum/)",
	"	59. [62. 不同路径](https://leetcode.cn/problems/unique-paths/)",
	"	60. [64. 最小路径和](https://leetcode.cn/problems/minimum-path-sum/)",
	"	61. [5. 最长回文子串](https://leetcode.cn/problems/longest-palindromic-substring/)",
	"	62. [1143. 最长公共子序列](https://leetcode.cn/problems/longest-common-subsequence/)",
	"	63. [72. 编辑距离](https://leetcode.cn/problems/edit-distance/)",
	"	64. [62. 不同路径](https://leetcode.cn/problems/unique-paths/)",
	"	65. [75. 颜色分类](https://leetcode.cn/problems/sort-colors/)",
	"	66. [31. 下一个排列](https://leetcode.cn/problems/next-permutation/)",
	"	67. [287. 寻找重复数](https://leetcode.cn/problems/find-the-duplicate-number/)",
}
